[build]
base = "angular"
  publish = "dist/browser"
  functions = "netlify/functions"
  command = "ng build"

[dev]
  framework = "#custom"
  command = "ng serve"
  targetPort = 4200
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200